### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by UrbanCondor** [chenkie/angular-cli-heroku#2]
Hi @chenkie , 

I wanted a very basic Angular 2 project that worked out-of-the-box with Heroku, so I thought I would clone this repository. However, I get the following errors upon npm install:

![image](https://cloud.githubusercontent.com/assets/18430094/21738086/e09c02ae-d4ba-11e6-8847-c308670e5fe0.png)

I also get the following error upon ng serve:

![image](https://cloud.githubusercontent.com/assets/18430094/21738104/10f9376e-d4bb-11e6-8fc5-8c1491d2905d.png)

However, the app (somewhat unexpectedly) appears to be working @ http://localhost:4200/

What do these errors mean and should / can they be corrected?

**Comment by chenkie** [comment]
Which version of the Angular CLI are you using? It's possible that an upgrade might solve it if you've got an older version.

**Comment by UrbanCondor** [comment]
![image](https://cloud.githubusercontent.com/assets/18430094/21738610/f8642d96-d4c2-11e6-9c25-93c6b8d17457.png)

**Comment by chenkie** [comment]
It looks like this is an issue with the CLI https://github.com/angular/angular-cli/issues/3674

I'll stay tuned for a fix there and include it here when it's ready.

**Comment by UrbanCondor** [comment]
Thanks Ryan

**Comment by chenkie** [comment]
Looks like there are some resolutions over in the CLI issue now. https://github.com/angular/angular-cli/issues/3674
